name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2  # Set up Docker Buildx to build images in parallel

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache  # Cache Docker layers to speed up builds
        key: ${{ runner.os }}-docker-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-docker-

    
    - name: Build and Tag Docker image
      run: |
        IMAGE_NAME=my-image-name
        TIMESTAMP=$(date +%s)
        docker build . --file Dockerfile --tag $IMAGE_NAME:$TIMESTAMP
        docker tag $IMAGE_NAME:$TIMESTAMP $IMAGE_NAME:latest  # Optionally tag with 'latest'

    - name: Push Docker image to Docker Hub
      run: |
        IMAGE_NAME=my-image-name
        TIMESTAMP=$(date +%s)
        docker push $IMAGE_NAME:$TIMESTAMP
        docker push $IMAGE_NAME:latest  # Push the 'latest' tag as well
