name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code from the repository
    - uses: actions/checkout@v4
    
    # Set up Docker Buildx (Optional, but useful for multi-platform builds)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    # Build the Docker image based on the provided Dockerfile
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag _Pyglot_:$(date +%s)
    
    # Optionally, push the Docker image to Docker Hub or other registry
    # Uncomment and configure these lines if you want to push the image to a registry
    # - name: Log in to Docker Hub
    #   uses: docker/login-action@v2
    #   with:
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASSWORD }}
    # 
    # - name: Push the Docker image
    #   run: docker push _Pyglot_:$(date +%s)

