name: Java CI with Maven

on:
  push:
    branches: [ "master" ]  # Update branch name if needed
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'  # Update if your project uses a different version
        distribution: 'temurin'
        cache: maven

    - name: Build and run tests with Maven
      run: mvn -B clean install -e -X  # Enable debug logs for better troubleshooting

    - name: Display test reports on failure
      if: failure()  # This step runs only if the previous step fails
      run: cat target/surefire-reports/*.txt

    # Optional: Upload Maven dependency graph for Dependabot
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
