name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'  # Adjust Java version if needed
        distribution: 'temurin'
        cache: maven

    - name: Validate Maven setup
      run: mvn validate  # Ensures Maven is set up correctly

    - name: Build and run tests
      run: mvn -B clean install -e -X  # Enables debug mode for detailed logs

    - name: Display test reports on failure
      if: failure()  # Run only if tests fail
      run: cat target/surefire-reports/*.txt

    - name: Upload test results
      if: always()  # Always run this step to provide feedback
      uses: actions/upload-artifact@v3
      with:
        name: surefire-reports
        path: target/surefire-reports/
